### ISSUE TITLE
The chat shows that i receive the commend but the menu/profile doesnt show.

### ISSUE THREAD

**Issue by Phxlxpp** [BeepIsla/csgo-commend-bot#350] opened 2020-04-15 00:17 UTC
**Detailed bug description**
The chat shows that i receive the commend but the menu/profile doesnt show.

**Error**
```
Chat says: Glückwunsch! Sie haben eine Anerkennung erhalten. but i dont receive them
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: v12.9.1
- Script version: `2.7.1` 

**Additional information**
You could say the number is stuck

**Comment by BeepIsla** [comment] 2020-04-15 00:20
Probably duplicate of #302 

I have no fix for this, I don't know why this happens.

The only somewhat good explanation would be commend-history was deleted and the bots are now changing their commends, so for example if a bot previously only did Teacher and now does Leader it will remove from one and add to the other.

**Comment by Phxlxpp** [comment] 2020-04-15 00:48
Okay but ty :)

**Closed** 2020-04-15 00:49 UTC
