### ISSUE TITLE
about proxy and config setting

### ISSUE THREAD

**Issue by erka15** [BeepIsla/csgo-commend-bot#168] opened 2019-12-08 12:07 UTC
**Config**
"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
.........
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 0,
	"cooldown": 28800000,
......

when i stat index.js it works well for  first chunk
but for second chunk i get this error"
[steamidusername] Failed to commend (20/20) { name: 'Error',
  message: 'Failed to send message: Timeout',
  stack:
   'Error: Failed to send message: Timeout\n    at Timeout.setTimeout [as _onTimeout] (C:\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:161:12)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)' }
 Chunk 2/2 finished with 0 successful commends and 20 failed commends"

is my config file ok?
can i send 100 commends at the same time with using proxy?

proxies.txt:
167.172.25.209:3128
167.99.186.130:8080
........
.......

**Version**
- NodeJS: v10.16.0
- Script version: 2.2.6

**Comment by BeepFelix** [comment] 2019-12-08 12:09
You can only send 20 commends per IP, according to your config (`switchProxyEveryXaccounts`) proxy already changes every 20 accounts so this is okay.

You should probably increase your `betweenChunks` to maybe at least 1 second and see if that helps.

**Comment by erka15** [comment] 2019-12-08 12:35
> You can only send 20 commends per IP, according to your config (`switchProxyEveryXaccounts`) proxy already changes every 20 accounts so this is okay.
> 
> You should probably increase your `betweenChunks` to maybe at least 1 second and see if that helps.

same error for every chunk (1,2,3....)

**Comment by BeepFelix** [comment] 2019-12-08 12:36
> same error for every chunk (1,2,3....)

With `betweenChunks` at 1 second or higher?

**Comment by erka15** [comment] 2019-12-08 12:36
> > same error for every chunk (1,2,3....)
> 
> With `betweenChunks` at 1 second or higher?

"betweenChunks": 2000,

**Comment by BeepFelix** [comment] 2019-12-08 12:37
Try changing `switchProxyEveryXaccounts` to something like `10`

**Comment by erka15** [comment] 2019-12-08 12:41
> Try changing `switchProxyEveryXaccounts` to something like `10`

Chunk 1/2 finished with 0 successful commends and 20 failed commends
 Chunk 2/2 finished with 0 successful commends and 20 failed commends
"switchProxyEveryXaccounts": 10
"perChunk": 20,
"betweenChunks": 2000,
"cooldown": 28800000,

**Comment by BeepFelix** [comment] 2019-12-08 12:43
Its possible that, due to frequent restarts the proxy has reached its limit (20 commends per 5 minutes). The proxy list is going from top to bottom one after another, your top one or two proxies might have reached their limit if you restarted it within less than 5 minutes.

**Comment by erka15** [comment] 2019-12-08 13:25
> Its possible that, due to frequent restarts the proxy has reached its limit (20 commends per 5 minutes). The proxy list is going from top to bottom one after another, your top one or two proxies might have reached their limit if you restarted it within less than 5 minutes.
> 
> Try changing the order in your proxies.txt so a new proxy is being used.

still same first one works second chunk fails

[SS in here](https://imgur.com/ZPo6Yrw)

**Comment by BeepFelix** [comment] 2019-12-08 13:27
Very weird, last test what if you change `perChunk` to something like `10`? Does that work?

**Comment by erka15** [comment] 2019-12-08 13:32
> Very weird, last test what if you change `perChunk` to something like `10`? Does that work?
 Chunk 1/4 finished with 10 successful commends and 0 failed commends
 Chunk 2/4 finished with 10 successful commends and 0 failed commends
 Chunk 3/4 finished with 0 successful commends and 10 failed commends
 Chunk 4/4 finished with 0 successful commends and 10 failed commends

**Comment by BeepFelix** [comment] 2019-12-08 13:33
I don't know what the cause of this could be, if you change everything back to how it was at the beginning and change `betweenChunks` back to 5 minutes it works like normal again, right?

**Comment by erka15** [comment] 2019-12-08 13:35
> I don't know what the cause of this could be, if you change everything back to how it was at the beginning and change `betweenChunks` back to 5 minutes it works like normal again, right?

its working when betweenChunk s 5 minutes without proxy.

**Comment by BeepFelix** [comment] 2019-12-08 13:35
I know, I just want to confirm that its not a proxy issue

**Comment by ramazan00** [comment] 2019-12-09 21:17
doesn't send without 5 minutes even though I use a proxy

**Comment by UnbreakCode** [comment] 2019-12-13 11:56
The Proxies are maybe "blocked" by CSGO/Steam. They can login on steam but if they are "blocked" a timeout will happen. Using another Proxies may fix the problem.

**Comment by erka15** [comment] 2019-12-13 12:57
> The Proxies are maybe "blocked" by CSGO/Steam. They can login on steam but if they are "blocked" a timeout will happen. Using another Proxies may fix the problem.

Already tried working ips. The result is same

**Comment by ramazan00** [comment] 2019-12-14 09:40
proxy Steam Login successful. gives error when sending commend

**Comment by UnbreakCode** [comment] 2019-12-14 23:51
> proxy Steam Login successful. gives error when sending commend



> Already tried working ips. The result is same

Can tell u that this is a proxy problem. Using **HTTP** Private Proxies will fix the problem.

**Comment by ramazan00** [comment] 2019-12-15 09:37
HTTP Custom Proxies
Where can I buy?

**Comment by erka15** [comment] 2019-12-16 22:56
> > proxy Steam Login successful. gives error when sending commend
> 
> > Already tried working ips. The result is same
> 
> Can tell u that this is a proxy problem. Using **HTTP** Private Proxies will fix the problem.

my proxies re working.(2 proxies and 2 chunk(40 commends))i have already tried myself.as you can see first chunk working.

Note: 167.172.25.209:3128 and 167.99.186.130:8080 just an example

**Comment by BeepIsla** [comment] 2019-12-17 00:11
> my proxies re working.(2 proxies and 2 chunk(40 commends))i have already tried myself.as you can see first chunk working.
> and it doesnt say "Loading proxies..."
> 
> Note: 167.172.25.209:3128 and 167.99.186.130:8080 just an example

This is a bug right now, it only counts up and never wraps back around, so for example 40 per 5 minutes is currently impossible to do. Will fix it later today.

**Comment by BeepIsla** [comment] 2019-12-17 01:17
> > my proxies re working.(2 proxies and 2 chunk(40 commends))i have already tried myself.as you can see first chunk working.
> > and it doesnt say "Loading proxies..."
> > Note: 167.172.25.209:3128 and 167.99.186.130:8080 just an example
> 
> This is a bug right now, it only counts up and never wraps back around, so for example 40 per 5 minutes is currently impossible to do. Will fix it later today.

This is now fixed.

**Comment by wiktor00013** [comment] 2019-12-21 21:00
not working
 Failed to login and due to proxy timeout (7/20) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '1.0.211.103',

**Comment by BeepIsla** [comment] 2019-12-21 21:02
> not working
> Failed to login and due to proxy timeout (7/20) {
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '1.0.211.103',

Get better proxies

**Comment by Pr0One** [comment] 2020-01-09 11:53
How can I put proxies with pass to proxies.txt? I have proxies with authentication.

**Comment by BeepIsla** [comment] 2020-01-09 12:00
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
    │                                              href                                              │
    ├──────────┬──┬─────────────────────┬────────────────────────┬───────────────────────────┬───────┤
    │ protocol │  │        auth         │          host          │           path            │ hash  │
    │          │  │                     ├─────────────────┬──────┼──────────┬────────────────┤       │
    │          │  │                     │    hostname     │ port │ pathname │     search     │       │
    │          │  │                     │                 │      │          ├─┬──────────────┤       │
    │          │  │                     │                 │      │          │ │    query     │       │
    "  https:   //    user   :   pass   @ sub.example.com : 8080   /p/a/t/h  ?  query=string   #hash "
    │          │  │          │          │    hostname     │ port │          │                │       │
    │          │  │          │          ├─────────────────┴──────┤          │                │       │
    │ protocol │  │ username │ password │          host          │          │                │       │
    ├──────────┴──┼──────────┴──────────┼────────────────────────┤          │                │       │
    │   origin    │                     │         origin         │ pathname │     search     │ hash  │
    ├─────────────┴─────────────────────┴────────────────────────┴──────────┴────────────────┴───────┤
    │                                              href                                              │
    └────────────────────────────────────────────────────────────────────────────────────────────────┘
    (all spaces in the "" line should be ignored — they are purely for formatting)

- *Via [NodeJS.org](https://nodejs.org/api/url.html#url_url_strings_and_url_objects)*

If that's too confusing: `http://username:password@127.0.0.1:8181`

**Comment by Pr0One** [comment] 2020-01-10 12:18
[barry2009nakagawa] Failed to login (19/20) {
  eresult: 43,
  name: 'Error',
  message: 'AccountDisabled',
  stack: 'Error: AccountDisabled\n' 

Why it happens? I use private http proxies.

**Comment by BeepIsla** [comment] 2020-01-10 12:19
Nothing to do with proxies, read the actual error. Your account is banned from Steam.

**Comment by Pr0One** [comment] 2020-01-10 12:19
Every account?

**Comment by Pr0One** [comment] 2020-01-10 12:20
So why if i join databaseManager and check for not working acc it says that all accounts are working...

**Comment by BeepIsla** [comment] 2020-01-10 12:23
> So why if i join databaseManager and check for not working acc it says that all accounts are working...

That should not happen, I will fix it so accounts are marked as invalid properly.

**Comment by Pr0One** [comment] 2020-01-10 12:24
Thank u, cant wait!

**Comment by BeepIsla** [comment] 2020-01-10 12:32
Fixed, accounts will now get marked as invalid if they receive `AccountDisabled` error.

**Comment by Pr0One** [comment] 2020-01-10 12:58
Why my accounts are getting disabled?

**Comment by BeepIsla** [comment] 2020-01-10 13:00
Ask Valve.

**Comment by Pr0One** [comment] 2020-01-10 13:02
Cause idk if its for too many signing in from randoms ip or blocked domain. xd

**Comment by Pr0One** [comment] 2020-01-10 13:25
Finished all chunks with a total of 333 successful and 328 failed commends :(

**Comment by Pr0One** [comment] 2020-01-10 13:43
still not working :/

**Comment by BeepIsla** [comment] 2020-01-10 14:01
> still not working :/

Don't hijack other issues. Make your own.

**Comment by BeepIsla** [comment] 2020-02-26 06:38
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.

**Closed by BeepIsla** 2020-02-26 06:38 UTC
Labels: bug, help wanted
