### ISSUE TITLE
The number of commends is not updated

### ISSUE THREAD

**Issue by spamtosite** [BeepIsla/csgo-commend-bot#202] opened 2020-01-08 21:38 UTC
```
The number of commends is not updated in CSGO Profile.
```
<a href="https://imgbb.com/"><img src="https://i.ibb.co/QF5K2J8/image.png" alt="image" border="0"></a>

```
If you look in the Steam profile, then the commends are visible.
```
<a href="https://ibb.co/7x35z7S"><img src="https://i.ibb.co/8nypBFm/image.jpg" alt="image" border="0"></a>

```
The process goes without errors.
```
<a href="https://ibb.co/jgsxqkr"><img src="https://i.ibb.co/GcN1GQ5/17.png" alt="17" border="0"></a>

```
**Config**
```
<a href="https://ibb.co/SVvVCPy"><img src="https://i.ibb.co/GCPCS0p/16.png" alt="16" border="0"></a>

**Version**
- NodeJS: `v13.3.0`
- Script version: `2.5.4` 

**Additional information**
I tried several methods "LOGIN" and "SERVER", but still the commends are not updated, although in the game itself I see messages that I got commends
Previously, everything worked well and there were no problems.
Use for personal non-commercial purposes

**Comment by BeepIsla** [comment] 2020-01-08 21:50
1. Thanks for this detailed post.

2. Duplicate of #119 

3. I don't know the cause of this or how to fix it sadly. As far as I know it randomly works again at some point.

**Closed by BeepIsla** 2020-01-08 21:50 UTC
