### ISSUE TITLE
Not all commends arrive at the target

### ISSUE THREAD

**Issue by ThiCCShib** [BeepIsla/csgo-commend-bot#119] opened 2019-10-22 14:36 UTC
when i use the commend bot and enter the "node index.js"command,it shows that everything is working at it says that the commends were sent through,but when i check my account nothing happned.
many thanks

**Comment by BeepFelix** [comment] 2019-10-22 14:46
What is your config

**Comment by ThiCCShib** [comment] 2019-10-22 16:40
"commend": {
        "friendly": 50,
        "teaching": 50,
        "leader": 50
    },
    "account": {
        "username": "",
        "password": "",
        "sharedSecret": ""
    },
    "fetcher": {
        "username": "PrimeAccount",
        "password": "PrimePassword",
        "sharedSecret": "",
        "maxTries": 10,
        "tryDelay": 2500,
        "askSteamGuard": true
    },
    "method": "SERVER",
    "target": "https://steamcommunity.com/id/probs_salty/",
    "serverID": "129.232.164.25:27015",
    "matchID": "0",
    "perChunk": 20,
    "betweenChunks": 300000,
    "cooldown": 28800000,
    "steamWebAPIKey": "8Dxxxxxxxxxxxxxx"
}

**Comment by BeepFelix** [comment] 2019-10-22 16:54
Does the output say "Successfully commended........."?

**Comment by ThiCCShib** [comment] 2019-10-22 17:21
yeah,succefull sent commend with response code 1

**Comment by BeepFelix** [comment] 2019-10-22 17:23
No idea

**Comment by dusty-dusty** [comment] 2019-10-23 09:05
Im also having the same issue

**Comment by dusty-dusty** [comment] 2019-10-23 09:07
I tried these and for auto I used a prime account to get the server. None of those worked.
"serverID": "[A:1:1621585931:12649]",
"serverID": auto

**Comment by BeepFelix** [comment] 2019-10-23 09:24
Multiple people having the same issue? Sounds like Valve added new security measures.

**Comment by dusty-dusty** [comment] 2019-10-23 10:36
> 
> 
> Multiple people having the same issue? Sounds like Valve added new security measures and this time instead of just erroring they just give a fake response, _great_.

Did you try it for yourself? Does it not work for you?

**Comment by BeepFelix** [comment] 2019-10-23 10:39
I didn't try it myself but there isn't much to do wrong, if it says it successfully sent it then it has according to CSGO, but if you don't receive any then there is a problem.

**Comment by dusty-dusty** [comment] 2019-10-23 11:04
> 
> 
> I didn't try it myself but there isn't much to do wrong, if it says it successfully sent it then it has according to CSGO, but if you don't receive any then there is a problem.

I just tried it again with 2 accounts and it worked. Maybe was an issue on there side for a while.

**Comment by BeepFelix** [comment] 2019-10-23 11:05
@ThiCCShib do you mind trying again and reporting if it worked or not?

**Comment by reloaded175** [comment] 2019-10-23 11:06
seems to be working for me in LOGIN mode
![Screenshot (32)](https://user-images.githubusercontent.com/56505641/67386773-39d93c80-f5b3-11e9-8210-4aec43545e96.png)
![Screenshot (34)](https://user-images.githubusercontent.com/56505641/67386778-3c3b9680-f5b3-11e9-8e64-8ee50115be71.png)

**Comment by ThiCCShib** [comment] 2019-10-24 17:31
when i tried a test on my main with 1-1-1 commends,it showed that it was successful,but when i checked the account no commends worked.when i did the exact same thing on my alt with the same config the 1-1-1 commends came through as successful and when i checked the account the commends worked,so idk if it has something to do with your account,its definantly got nothing to do with your cs config,because i reset my config on my main and the commends still didnt work.

**Comment by ThiCCShib** [comment] 2019-10-24 18:22
i just did the same thing once again to see if there was any differences in the cmd tab.
this wasthe commends i sent on my main,that didnt count:  https://prnt.sc/pnouyv
this was the one i did on my alt and the commends counted:    https://prnt.sc/pnovrv
the one thing i saw that was different between them both was near the end of the line where it gives u comfirmation that the account has been successfully commended,the time it didnt work it says "remaining commends: 2"where as when i did the same to my alt and the commends counted,it says "remaining commends: 1"
idk if this helps u at all

**Comment by BeepFelix** [comment] 2019-10-24 18:24
Doesn't help as you have 3 commends per 24 hours, this one account was just used already within the past 24 hours so it has a lower remaining commend count.

**Comment by BeepFelix** [comment] 2019-10-25 14:52
> my friend started commending that acc with his accounts and it workes nearly fine tho. weird af.
> https://i.imgur.com/qm1a8Xc.png
> https://i.imgur.com/p4WU18y.png

What is weird here? Gained 14 commends.

**Comment by Craxto** [comment] 2019-10-25 14:53
yeah but when I wanna commend that dude, my commends arent counting :/

**Comment by BeepFelix** [comment] 2019-10-25 14:54
14 did count. What is wrong here? Did you set a different amount in your config?

**Comment by Craxto** [comment] 2019-10-25 14:55
no, my friend commended him. He has another database of accs.

**Comment by BeepFelix** [comment] 2019-10-25 14:56
So your friends commends are counting but not your own?

**Comment by Craxto** [comment] 2019-10-25 14:56
yep, exactly :/

**Comment by BeepFelix** [comment] 2019-10-25 14:57
But it does say success when you do it but they don't count regardless?

**Comment by Craxto** [comment] 2019-10-25 14:57
yep.

**Comment by Craxto** [comment] 2019-10-25 15:01
https://i.imgur.com/f8aNv0g.png before I started mine & stayed the same after success tho.
console said otherwise: https://i.imgur.com/0PAyFYy.png

**Comment by Craxto** [comment] 2019-10-25 15:07
just tested it with a fresh acc, my bot still works fine af, didnt change anything except the one getting commends. 
https://i.imgur.com/6Pdv635.png
https://i.imgur.com/43J8ycV.png

**Comment by BeepFelix** [comment] 2019-10-25 15:08
Not much I can say to this, I don't know why this happens and I doubt we will ever find out why.

**Comment by Craxto** [comment] 2019-10-25 15:12
true that :/

**Comment by xselectx** [comment] 2019-10-31 17:49
My issue started yesterday after steam update but for me it's sometimes totally random. First X commends today was working normally, but another either was not sended or only half of them arrived.

**Comment by Lefeo** [comment] 2019-11-01 14:29
here 2

**Comment by ThiCCShib** [comment] 2019-11-05 14:44
i still cant commend,shows that it was succesful but nothing appears RIP

**Comment by BeepFelix** [comment] 2019-11-05 15:25
> i still cant commend,shows that it was succesful but nothing appears RIP

All don't appear or only some?

**Comment by xSuspect** [comment] 2019-11-22 18:08
what we discovered(https://prnt.sc/q0phw6)
new version:2.2.4 (at the new version the commends are sent and then blocked at 19-20 and does not continue automatically, must be manually)
old version:First (at which old it is sent automatically but you do not receive commands)

maybe it will help

**Comment by BeepFelix** [comment] 2019-11-23 05:48
What version is "old version"?

**Comment by xSuspect** [comment] 2019-11-23 14:54
> What version is "old version"?
the first version you created
https://prnt.sc/q10jwp
https://www.mpgh.net/forum/showthread.php?t=1453988

**Comment by BeepFelix** [comment] 2019-11-23 14:57
The `package.json` has a `version` key, what does it say?

**Comment by xSuspect** [comment] 2019-11-23 15:25
> The `package.json` has a `version` key, what does it say?
`{
  "name": "csgo-commend-bot",
  "version": "1.0.0",
  "description": "Experimental csgo commend bot rewrite",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "github.com/BeepFelix",
  "license": "AGPL-3.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/BeepFelix/csgo-commend-bot.git"
  },
  "dependencies": {
    "bytebuffer": "^5.0.1",
    "inquirer": "^6.3.1",
    "protobufjs": "github:protobufjs/protobuf.js#ProtoBuf4",
    "request": "^2.88.0",
    "serialize-error": "^4.1.0",
    "sqlite": "^3.0.3",
    "steam-totp": "^2.1.0",
    "steam-user": "^4.8.0",
    "steamid": "^1.1.0",
    "unzipper": "^0.10.0"
  }
}
`

**Comment by BeepFelix** [comment] 2019-11-23 15:28
> 1.0.0

I think that's too old to work with.

**Comment by xSuspect** [comment] 2019-11-23 15:37
version:2.2.4 works but does not send automatically, must be done manually every 5 minutes :(

**Comment by BeepFelix** [comment] 2019-11-23 15:44
Are you talking about the same error as #147? Because I think this issue is related to something else.

**Comment by xSuspect** [comment] 2019-11-23 16:04
I do not have this error, it works for me but it is blocked at 19/20
https://prnt.sc/q117sy
https://prnt.sc/q117vy

**Comment by BeepFelix** [comment] 2019-11-23 16:04
Yes thats what that issue refers to, the error shown in the screenshot is irrelevant but its stuck at 19/20. So move conversation over there.

**Comment by ThiCCShib** [comment] 2019-11-25 14:53
a couple minutes ago i used the commend bot and because of the new update where u can see when u recieve a commend,the game itself showd that i have been commended but however my commends did not change :(

**Comment by BeepFelix** [comment] 2019-11-25 14:54
Commends may not update instantly, give it a few seconds to a minute.

**Comment by samet231** [comment] 2019-12-10 21:01
"a couple minutes ago i used the commend bot and because of the new update where u can see when u recieve a commend,the game itself showd that i have been commended but however my commends did not change :("  same issues

**Comment by Siezek1** [comment] 2020-01-06 13:52
I have the same problem ;/

**Comment by Siezek1** [comment] 2020-01-06 13:54
I will add from myself that I used the bot on my second account and there it showed that I got recommend and I actually got recommends, and in my account he gives these recommends, but does not get them. Maybe it's vavle fault

**Comment by spamtosite** [comment] 2020-01-09 10:12
Perhaps the problem is with new accounts that are without prime
Can anyone check this out?

**Comment by BeepIsla** [comment] 2020-01-09 10:22
> Perhaps the problem is with new accounts that are without prime
> Can anyone check this out?

None of my accounts have prime, everything works flawless.

> Maybe in this way Valve wants to deprive them of the opportunity to increase their trust-factor and not allow them to earn in this way

A friend has over 40K (Botted) commends, their Trust Factor is worse than mine with just barely 100 (Legit) commends. I doubt commends increase Trust Factor at all, or if they do it depends on *who* gives out the commend and bot accounts are automatically ignored when calculating Trust Factor. Nobody knows for sure though.

**Comment by Siezek1** [comment] 2020-01-14 16:41
Someone has already rectified this error? because I have it all the time ...

**Comment by rakage** [comment] 2020-01-22 11:30
Im having this too, i have 21k commends. I was using my accs generator long time ago, and im using them again now. Is this because my accs generator been commended my main acc long time ago, and im not recieve any commends again from that accounts? 

But when i see on my csgo personal stats in commend tab, im recieving commends, but in csgo game, my commends arent updated. Sorry for my bad english

**Comment by BeepIsla** [comment] 2020-01-22 11:34
>  Is this because my accs generator been commended my main acc long time ago, and im not recieve any commends again from that accounts?

Yes. You cannot commend the same person multiple times. You can't do it yourself when you commend someone so how would a bot do this, that makes no sense.

There is a reason why the `accounts.sqlite` is so important because it stores more than just account details, it also stores which account has commended which target to make sure accounts don't get reused.

If the commend-history is missing the script will reuse already used accounts and you will get the exact problem you're having right now. You have to read **exactly** what the output of the console says. It will say `Already commended` and `Response Code: 2` which clearly tells you what the problem is.

**Comment by rakage** [comment] 2020-01-24 03:00
> > Is this because my accs generator been commended my main acc long time ago, and im not recieve any commends again from that accounts?
> 
> Yes. You cannot commend the same person multiple times. You can't do it yourself when you commend someone so how would a bot do this, that makes no sense.
> 
> There is a reason why the `accounts.sqlite` is so important because it stores more than just account details, it also stores which account has commended which target to make sure accounts don't get reused.
> 
> If the commend-history is missing the script will reuse already used accounts and you will get the exact problem you're having right now. You have to read **exactly** what the output of the console says. It will say `Already commended` and `Response Code: 2` which clearly tells you what the problem is.

So its not possible even tho i commended the account a year ago? I thought i can recommend again after a week.

**Comment by BeepIsla** [comment] 2020-01-24 03:07
> So its not possible even tho i commended the account a year ago? I thought i can recommend again after a week.

You can never commend the same person again.

**Comment by Carlosenes** [comment] 2020-02-11 18:58
the same thing happened to me successfully says the commends but then I go to the account to see the compliments and I did not receive the compliments

someone can help me?

**Comment by BeepIsla** [comment] 2020-02-26 06:39
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.

**Closed by BeepIsla** 2020-02-26 06:39 UTC
Labels: bug, help wanted
