### ISSUE TITLE
not sending comments (SERVER METHOD)

### ISSUE THREAD

**Issue by xm1nn** [BeepIsla/csgo-commend-bot#149] opened 2019-11-16 22:00 UTC
Last week I was able to send it by server method
But for now, he's always making mistakes.
[https://i.imgyukle.com/2019/11/17/RRmRO8.png](url)
Dude what is the problem?
If the program is wrong, will it be fixed?

**Comment by BeepFelix** [comment] 2019-11-16 22:02
There are many possible reasons for it to happen such as:
- Target left the server
- Server is now full
- Server does not have enough slots (Unconfirmed)
- Server is a Valve Matchmaking server
- Target hit the commend limit (20 per 5 minutes)
- Server hit the total commend limit (150 - Unconfirmed)
- Steam is offline
- CSGO is offline
- I don't know maybe more?

That's all I know.

**Comment by xm1nn** [comment] 2019-11-16 22:11
- Inside the target server

- Only 2 person on the server(32/2)

- anyone can access the server.

- The server is a community server

- The Program doesn't send anything. (0-0-0)

- Server has not  limit commendexceeded 

- Steam ON

- CSGO is Online

The problem has only been happening for a few days.
Anyway mate, thank you for everything.

Also sorry for my bad English 🚨

**Comment by BeepFelix** [comment] 2019-11-16 22:19
Show your config, censor things such as API key first.

**Comment by xm1nn** [comment] 2019-11-16 22:29
![hata](https://user-images.githubusercontent.com/55345056/68999990-bb359d80-08d9-11ea-895f-66a25e3a2f41.PNG)

**Comment by BeepFelix** [comment] 2019-11-16 22:34
No server port?

**Comment by xm1nn** [comment] 2019-11-16 22:39
It doesn't matter, he makes two kinds of mistakes.
Gives the same error in two cases
-27015

**Comment by BeepFelix** [comment] 2019-11-16 22:40
Well, I don't know why this happens then to be honest.

**Comment by cazorlassj** [comment] 2019-11-20 22:49
Something similar happened to me. I was sending commends to my friend and out of nowhere the bot gave me "timeout". (my friend was connected on the zonerbot server)
I told my friend to connect to another server and 200 commends were sent normally, my friend connected to a server of those that increases the stattrack
my config:
![Screenshot_29](https://user-images.githubusercontent.com/51689868/69281351-e3b5e400-0bc6-11ea-9c34-b122354f6ea9.png)

**Comment by cazorlassj** [comment] 2019-11-20 23:00
It seems that the server limit is real. about 190 commends were sent and now I get an error
i enter with my account and i try to commend my friend and he doesn't receive it
valve added a limit?

**Comment by BeepFelix** [comment] 2019-11-21 03:37
That sucks, I'll put the possible causes for timeout in the README and maybe change it so when using LOGIN method the server gets switched every 150 commends.

**Comment by RadicalRedemption** [comment] 2019-12-17 13:01
Instead of sending, it removed lots of my commends. Maybe Valve fixed it.

**Comment by BeepIsla** [comment] 2020-02-26 06:38
Closing this due to major changes on Valves side and on the commend bot itself. If the issue continues please reopen.

**Closed by BeepIsla** 2020-02-26 06:38 UTC
Labels: help wanted
